const columns1 = [
    {title: '일련번호',
     dataIndex: 'serial_no',
     key: 'serial_no'},
    {title: '이름',
     dataIndex: 'name',
     key: 'name'},
    {title: '구분1',
     dataIndex: 'category',
     key: 'category'},
    {title: '구분2 (지역,지지도)',
     dataIndex: 'category2',
     key: 'category2'},
    {title: '추천인  -최대2명',
     dataIndex: 'recommender',
     key: 'recommender',
     editable: true},
    {title: '메모 (민병덕,김민영) - 작성일 필수',
     dataIndex: 'memo_specific',
     key: 'memo_specific'},
    {title: '메모 (캠프) -작성일, 작성자 정보 필수',
     dataIndex: 'memo',
     key: 'memo'},
    {title: '휴대폰 1',
     dataIndex: 'phone1',
     key: 'phone1'},
    {title: '휴대폰 2',
     dataIndex: 'phone2',
     key: 'phone2'},
    {title: '비고 - 직업,나이 등',
     dataIndex: 'remark',
     key: 'remark'},
    {title: '핸드폰 그룹명',
     dataIndex: 'phone_group',
     key: 'phone_group'}];
   
const columns2 = [  
    {title: '[2020당원] 이름',
     dataIndex: 'name_2020',
     key: 'name_2020'},
    {title: '[2020당원] 구분',
     dataIndex: 'category_2020',
     key: 'category_2020'},
    {title: '[2020당원] 추천인A',
     dataIndex: 'recommender_a_2020',
     key: 'recommender_a_2020'},
    {title: '[2020당원]  추천인B',
     dataIndex: 'recommender_b_2020',
     key: 'recommender_b_2020'},
    {title: '[2020당원] 주민번호',
     dataIndex: 'ssnum_2020',
     key: 'ssnum_2020'},
    {title: '[2020당원] 주소',
     dataIndex: 'address_2020',
     key: 'address_2020'},
    {title: '[2020당원] 은행, 예금주, 계좌',
     dataIndex: 'account_2020',
     key: 'account_2020'},
    {title: '[2020당원] 휴대전화',
     dataIndex: 'phone_2020',
     key: 'phone_2020'},
    {title: '[2020당원] 취합일',
     dataIndex: 'integrate_day_2020',
     key: 'integrate_day_2020'},
    {title: '[2020당원] 비고',
     dataIndex: 'remark_2020',
     key: 'remark_2020'},
    {title: '[2020당원] 제출일',
     dataIndex: 'submit_day_2020',
     key: 'submit_day_2020'}];
   
const columns3 = [
    {title: '[2016당원] 이름',
     dataIndex: 'name_2016',
     key: 'name_2016'},
    {title: '[2016당원] 구분',
     dataIndex: 'category_2016',
     key: 'category_2016'},
    {title: '[2016당원] 휴대폰',
     dataIndex: 'phone_2016',
     key: 'phone_2016'},
    {title: '[2016당원] 추천인',
     dataIndex: 'recommender_2016',
     key: 'recommender_2016'},
    {title: '[2016당원] 주민번호',
     dataIndex: 'ssnum_2016',
     key: 'ssnum_2016'},
    {title: '[2016당원] 주소',
     dataIndex: 'address_2016',
     key: 'address_2016'},
    {title: '회사.직책',
     dataIndex: 'company_position',
     key: 'company_position'},
    {title: '회사번호',
     dataIndex: 'company_num',
     key: 'company_num'},
    {title: 'Fax번호',
     dataIndex: 'company_fax',
     key: 'company_fax'},
    {title: '회사주소',
     dataIndex: 'company_address',
     key: 'company_address'},
    {title: '이메일',
     dataIndex: 'email',
     key: 'email'}]
   
export { columns1, columns2, columns3 };